### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminlove520** [VulnTotal-Team/yarb#10]
前段时间都是正常的，然后现在运行报错：
![1659328798281](https://user-images.githubusercontent.com/32920883/182073597-d1ba2ecd-3cda-41b7-8888-ad532a40e6fb.png)

**Comment by firmianay** [comment]
用python3.8及以上

**Comment by adminlove520** [comment]
邮件配置好之后报了个错  Server not connected；之前是是正常的呢

**Comment by firmianay** [comment]
邮箱的问题吧
