### ISSUE TITLE
飞书无法推送

### ISSUE THREAD

**Issue by xiaqiqi-1** [VulnTotal-Team/yarb#12]
添加了飞书的配置项，无法通过飞书推送消息

**Comment by firmianay** [comment]
看看日志？

这里改成true了吗
```
    "bot": {
        "feishu": {
            "enabled": false,
            "secrets": "FEISHU_KEY",
            "key": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
```

**Comment by xiaqiqi-1** [comment]
改成true

**Comment by xiaqiqi-1** [comment]
![image](https://user-images.githubusercontent.com/73576619/218396837-3cddd99a-5386-4b09-8fc4-30544e16a40b.png)
![image](https://user-images.githubusercontent.com/73576619/218396980-7427e3d0-72a2-4e11-889d-ca81e20f1a92.png)
最后执行完也没有报错

**Comment by firmianay** [comment]
“0 feeds, 0 articles“，没有可以推送的东西

**Comment by xiaqiqi-1** [comment]
> “0 feeds, 0 articles“，没有可以推送的东西

好的谢谢

**Comment by xiaqiqi-1** [comment]
> “0 feeds, 0 articles“，没有可以推送的东西

好的谢谢
