### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminlove520** [VulnTotal-Team/yarb#7]
centos运行yarb.py时报错：
[-] failed: https://wechat2rss.xlab.app/feed/1063f6d607a637eb0ddc129b58bd081820dd31cb.xml
HTTPSConnectionPool(host='wechat2rss.xlab.app', port=443): Read timed out. (read timeout=10)
这样的错误

**Comment by firmianay** [comment]
开代理吧，如果不行可以到这里提：https://github.com/ttttmr/Wechat2RSS

**Comment by adminlove520** [comment]
是不是我需要放行443和80呀

**Comment by firmianay** [comment]
有些站点连不上是正常的，可以看看自动运行的结果：https://github.com/VulnTotal-Team/yarb/runs/7382714895?check_suite_focus=true
